### ISSUE TITLE
[BUG] Exception thrown when using playwright in a single-file published program

### ISSUE THREAD

**Issue by jeroenpelgrims** [microsoft/playwright-dotnet#2255]
**Context:**
- Playwright Version: 1.24.1
- Operating System: Windows 10
- .NET version: .NET 6
- Browser: All
- Extra: 

**Code Snippet**

See code to reproduce this bug here: https://github.com/resurge/PlaywrightSingleFilePathError 

**Describe the bug**
When publishing a project as single file and running the published executable the following error will be shown:
```
Unhandled exception. System.ArgumentException: The path is empty. (Parameter 'path')
   at System.IO.Path.GetFullPath(String path)
   at System.IO.FileInfo..ctor(String originalPath, String fullPath, String fileName, Boolean isNormalized)
   at System.IO.FileInfo..ctor(String fileName)
   at Microsoft.Playwright.Helpers.Driver.GetExecutablePath() in /_/src/Playwright/Helpers/Driver.cs:line 41
   at Microsoft.Playwright.Transport.StdIOTransport.GetProcess() in /_/src/Playwright/Transport/StdIOTransport.cs:line 119
   at Microsoft.Playwright.Transport.StdIOTransport..ctor() in /_/src/Playwright/Transport/StdIOTransport.cs:line 44
   at Microsoft.Playwright.Playwright.CreateAsync() in /_/src/Playwright/Playwright.cs:line 44
   at Program.<Main>$(String[] args) in C:\Users\jeroe\Documents\repos\PlaywrightSingleFilePathError\Program.cs:line 3
   at Program.<Main>(String[] args)
```
I would expect the program to behave the same way as a regular Debug or Release build.  
But choosing to publish as a single file causes the behaviour of the executable to change. (And not work)

The following tickets were about the same bug but were closed because of no code to reproduce:
- https://github.com/microsoft/playwright-dotnet/issues/1952
- https://github.com/microsoft/playwright-dotnet/issues/1527

EDIT: Some other issues I found relating to this bug:
- https://github.com/microsoft/playwright-dotnet/issues/1069
  Not sure how the solution here works because `Playwright.CreateAsync` doesn´t accept parameters.
- https://github.com/microsoft/playwright-dotnet/issues/1274
   This ticket is closed with comment "not supported", but no reason is given as to why not.

**Comment by kblok** [comment]
My two cents here. I don't think an end-to-end testing library needs to support single-file publishing.

**Comment by resurge** [comment]
While that seems to be the [main reason](https://playwright.dev/docs/intro) Playwright was created it is used for more that that.  
I myself use it for scraping or transforming html to PDF. I would like to be able to share a single executable with users instead of having to make a zip file or installer as release.

The linked issues show that there is a need for this type of publishing.

**Comment by travisnielsen** [comment]
Echoing @jeroenpelgrims comments. We're using Playwright for generating .png files as part of the [Azure PlantUML](https://github.com/plantuml-stdlib/Azure-PlantUML) project and it would be great if we could offer a single executable to users who wish to generate their own diagram sprites.

**Comment by ianis58** [comment]
@kblok do you still have a patch for the issue #2493 ?
I think it's the same issue as this one.

**Comment by kblok** [comment]
@mxschmitt, the solution I was using was saving the driver in a shared location, `LocalApplicationData`. I don't know if that's what we'd want to do here.

**Comment by vmeganathan81** [comment]
Hi @kblok ,

Is this issue referred in #2493 ... done?

**Comment by kblok** [comment]
@vmeganathan81 I bet so.

**Comment by vmeganathan81** [comment]
Any ETA on this?

**Comment by vmeganathan81** [comment]
> @vmeganathan81 I bet so.

Okay, let me test with latest version... thanks

**Comment by vmeganathan81** [comment]
@jeroenpelgrims ... Are we going to resolve this or it would take more time?

**Comment by jeroenpelgrims** [comment]
> @jeroenpelgrims ... Are we going to resolve this or it would take more time?

I'll try to test tomorrow.
I actually haven't worked on the project this was for since the creation of this issue.

You verified it working on your end?

**Comment by vmeganathan81** [comment]
@mxschmitt ,

The solution @kblok mentioned is that merged and available with latest version?

**Comment by vmeganathan81** [comment]
@mxschmitt any update on this open issue?

**Comment by jsoctocat** [comment]
This issue still persist as of this comment (version 1.41.2)

**Comment by mxschmitt** [comment]
Starting from v1.44 this should be fixed: https://github.com/microsoft/playwright-dotnet/pull/2909

Browsers need to be installed via `Microsoft.Playwright.Program.Main(["install"]);`

**Comment by matthewteeter** [comment]
I still get this issue using v1.44 when running `Microsoft.Playwright.Program.Main(["install"])`.

Docker build error: 
> [final 3/4] RUN /app/PayPowerBill install:
1.565 Unhandled Exception: System.NotSupportedException: CodeBase is not supported on assemblies loaded from a single-file bundle.
1.565    at System.Reflection.Runtime.Assemblies.RuntimeAssemblyInfo.get_CodeBase() + 0x27
1.565    at Microsoft.Playwright.Helpers.Driver.GetExecutablePath() + 0xa8
1.565    at Microsoft.Playwright.Transport.StdIOTransport.GetProcess(String) + 0x36
1.565    at Microsoft.Playwright.Transport.StdIOTransport..ctor() + 0x62
1.565    at Microsoft.Playwright.Playwright.<CreateAsync>d__0.MoveNext() + 0x4f
1.565 --- End of stack trace from previous location ---
1.565    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x1c
1.565    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0xbe
1.565    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task, ConfigureAwaitOptions) + 0x4e
1.565    at Program.<<Main>$>d__0.MoveNext() + 0xe5
1.565 --- End of stack trace from previous location ---
1.565    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x1c
1.565    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0xbe
1.565    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task, ConfigureAwaitOptions) + 0x4e
1.565    at Program.<Main>(String[] args) + 0x24
1.565    at PayPowerBill!<BaseAddress>+0x4f86bc

Dockerfile:
```#syntax=docker/dockerfile:1
FROM mcr.microsoft.com/dotnet/runtime:8.0-jammy AS base
USER app
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:8.0 as build
# Install NativeAOT build prerequisites
USER root
RUN apt-get update && apt-get install -y --no-install-recommends clang zlib1g-dev

WORKDIR /src
COPY ["PayPowerBill.csproj", "."]
RUN dotnet restore "./PayPowerBill.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "PayPowerBill.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "PayPowerBill.csproj" -c Release -o /app/publish -r linux-x64 

FROM base AS final
USER root
WORKDIR /app
COPY --from=publish /app/publish .
##Need to trigger Playwright install thru code to avoid dependency on sdk in final image - see www.meziantou.net/distributing-applications-that-depend-on-microsoft-playwright.htm
RUN /app/PayPowerBill install
RUN <<-DEPS
	apt-get update &&
	apt-get -y install libasound2 libx11-xcb1 libxcursor1 libgtk-3-0 libpangocairo-1.0-0 libcairo-gobject2 libgdk-pixbuf-2.0-0 libdbus-glib-1-2 &&
	rm -rf /var/lib/apt/lists/* &&
	echo "workaround"
DEPS
ENTRYPOINT ["PayPowerBill"]
```
How the program calls install at startup:
```
using var playwright = await Playwright.CreateAsync();
var b = playwright.Firefox;
if (args.Any() && args?[0] == "install")
{
    Environment.Exit(Microsoft.Playwright.Program.Main(new[] { "install" }));//, b.Name }));
}
...
```

**Comment by mxschmitt** [comment]
@matthewteeter we need a full repro, ideally via a small git repository.

**Comment by matthewteeter** [comment]
Here is a full repro: https://github.com/matthewteeter/Playwright1.44AotRepro
Running the program as normal throws an exception on the first line in Program.cs.  Trying to install the browsers by invoking it with "install" (as shown by the Dockerfile) fails with:
```[final 3/3] RUN /app/PayPowerBill install:
0.816 Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
0.816    at Microsoft.Playwright.Transport.Connection.<WrapApiCallAsync>d__52`1.MoveNext() + 0x223
0.816 --- End of stack trace from previous location ---
0.816    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x1c
0.816    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0xbe
0.816    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task, ConfigureAwaitOptions) + 0x4e
0.816    at Microsoft.Playwright.Transport.Connection.<InitializePlaywrightAsync>d__43.MoveNext() + 0x11b
0.816 --- End of stack trace from previous location ---
0.816    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x1c
0.816    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0xbe
0.816    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task, ConfigureAwaitOptions) + 0x4e
0.816    at Microsoft.Playwright.Playwright.<CreateAsync>d__0.MoveNext() + 0x21d
0.816 --- End of stack trace from previous location ---
0.816    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x1c
0.816    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0xbe
0.816    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task, ConfigureAwaitOptions) + 0x4e
0.816    at Program.<<Main>$>d__0.MoveNext() + 0xdf
0.816 --- End of stack trace from previous location ---
0.816    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x1c
0.816    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0xbe
0.816    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task, ConfigureAwaitOptions) + 0x4e
0.816    at Program.<Main>(String[] args) + 0x24
0.816    at PayPowerBill!<BaseAddress>+0x2c672c```

**Comment by mxschmitt** [comment]
@matthewteeter AOT is not supported yet see here: https://github.com/microsoft/playwright-dotnet/issues/2714

**Comment by mxschmitt** [comment]
I'll close this issue, since this issue (sigle-file published program) has been resolved. See https://github.com/microsoft/playwright-dotnet/issues/2255#issuecomment-2056544386 for notes.
